name: Daily Portfolio Stock Price Fetch

on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  update-prices:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements/prices_requirements.txt

      - name: Run pipeline
        env:
          host: ${{ secrets.DB_HOST }}
          dbname: ${{ secrets.DB_NAME }}
          user: ${{ secrets.DB_USER }}
          password: ${{ secrets.DB_PASSWORD }}
          port: ${{ secrets.DB_PORT }}
          BRAPI_KEY: ${{ secrets.BRAPI_KEY }}
          PORT_BOT_TOKEN: ${{ secrets.PORT_BOT_TOKEN }}
          PORT_BOT_CHAT: ${{ secrets.PORT_BOT_CHAT }}
        run: python pipelines/prices_pipeline.py
